# Generated by Django 3.1.7 on 2021-06-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='generate_unique_code', max_length=8, unique=True),
        ),
    ]
